/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package help;

import caratula.GetFiltrosCombos;
import entidades.Idc;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import entidades.Volumen;
import idc.DefineTablaIdc;
import idc.MouseListenerAction;
import idc.VerIDC;
import javax.swing.JComboBox;

/**
 *
 * @author aguilangeles@gmail.com
 */
public class IdcTable extends javax.swing.JFrame {

  private final String and = "' and ca.idVolumen = ";
  private Volumen volumen;
  private int idsede;
  private GetFiltrosCombos filtros;

  /**
   * Creates new form CaratulasGenerales
   */
  public IdcTable() {
  }

  public IdcTable(final Volumen volumen) {
    initComponents();
    this.volumen = volumen;
    setFrame(volumen);
    setmouselistener(volumen);
    this.idsede = volumen.getIdSede();
    setFiltros(volumen);
    verTodosLosIdcs(volumen);
    verIdcPorTipo(volumen);
    verIdcPorSubtipo(volumen);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    ppanel = new javax.swing.JPanel();
    atras = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaIdc = new javax.swing.JTable();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    tipo = new javax.swing.JComboBox();
    jLabel2 = new javax.swing.JLabel();
    subtipo = new javax.swing.JComboBox();
    viewAll = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    atras.setText("Atras");
    atras.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        atrasActionPerformed(evt);
      }
    });

    tablaIdc.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {

      }
    ));
    jScrollPane1.setViewportView(tablaIdc);

    jPanel1.setOpaque(false);

    jLabel1.setText("Filtro por Tipo");

    tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jLabel2.setText("Filtro por Subtipo");

    subtipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    viewAll.setText("Ver Todos");
    viewAll.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        viewAllActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(51, 51, 51)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(subtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(viewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(tipo)
      .addComponent(subtipo, javax.swing.GroupLayout.Alignment.TRAILING)
      .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(viewAll, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout ppanelLayout = new javax.swing.GroupLayout(ppanel);
    ppanel.setLayout(ppanelLayout);
    ppanelLayout.setHorizontalGroup(
      ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ppanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
          .addGroup(ppanelLayout.createSequentialGroup()
            .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    ppanelLayout.setVerticalGroup(
      ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppanelLayout.createSequentialGroup()
        .addGap(9, 9, 9)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(atras)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(ppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(ppanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
    dispose();
  }//GEN-LAST:event_atrasActionPerformed

  private void viewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllActionPerformed
    verTodosLosIdcs(volumen);
  }//GEN-LAST:event_viewAllActionPerformed
  /**
   * @param args the command line arguments
   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//     */
//    try
//      {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//        {
//        if ("Nimbus".equals(info.getName()))
//          {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//          }
//        }
//      } catch (ClassNotFoundException ex)
//      {
//      java.util.logging.Logger.getLogger(CaratulasGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (InstantiationException ex)
//      {
//      java.util.logging.Logger.getLogger(CaratulasGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (IllegalAccessException ex)
//      {
//      java.util.logging.Logger.getLogger(CaratulasGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (javax.swing.UnsupportedLookAndFeelException ex)
//      {
//      java.util.logging.Logger.getLogger(CaratulasGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      }
//    //</editor-fold>
//
//    /* Create and display the form */
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        new CaratulasGenerales().setVisible(true);
//      }
//    });
//  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton atras;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPanel ppanel;
  private javax.swing.JComboBox subtipo;
  private javax.swing.JTable tablaIdc;
  private javax.swing.JComboBox tipo;
  private javax.swing.JButton viewAll;
  // End of variables declaration//GEN-END:variables

  private void verTodosLosIdcs(Volumen volumen) {
    List<Idc> idcs = VerIDC.getIdcWhere(" where i.idVolumen = " + volumen.getId());
    DefineTablaIdc tabla = new DefineTablaIdc(tablaIdc, idcs);
  }

  private void verIdcPorTipo(final Volumen volumen) {
    setComboActionListener(tipo, "where ca.tipo_doc = '", and, volumen);
  }

  private void verIdcPorSubtipo(final Volumen volumen) {
    setComboActionListener(subtipo, " where ca.subtipo_doc = '", and, volumen);
  }

  private void setFrame(Volumen volumen) {
    VersionEImageIcon vi = new VersionEImageIcon(this, "Idc " + volumen.getRuta());
    ppanel.setBackground(VersionEImageIcon.setcolor());
    setLocationRelativeTo(null);
  }

  private void setFiltros(final Volumen volumen) {
    this.filtros = new GetFiltrosCombos(volumen);
    this.tipo.setModel(filtros.getTipoDocumento());
    this.subtipo.setModel(filtros.getSubTiposDocumento());
  }

  private void setmouselistener(final Volumen volumen) {
    tablaIdc.addMouseListener(
            new MouseListenerAction(tablaIdc, volumen));

  }

  private void setComboActionListener(final JComboBox filtro, final String where,
          final String and, final Volumen volumen) {
    filtro.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        String condicion = where + filtro.getSelectedItem() + and + volumen.getId();
        List<Idc> idcs = VerIDC.getIdcWhere(condicion);
        DefineTablaIdc tabla = new DefineTablaIdc(tablaIdc, idcs);
      }
    });
  }
}
