/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package volumen;

import entidades.Volumen;
import help.VersionEImageIcon;
import caratula.Caratulas;
import help.IdcTable;


import javax.swing.JButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author aguilangeles@gmail.com
 */
public class PanelVolumenes extends javax.swing.JFrame {

  private Volumen volumen;

  /**
   * Creates new form PanelVolumenes
   *
   * @param volumen
   * @param boton
   */
  public PanelVolumenes(Volumen volumen, JButton boton) {
    initComponents();
    this.volumen = volumen;
    setResizable(false);
    setFrame(volumen);
    setLocationRelativeTo(boton);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    ppanel = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    total = new javax.swing.JButton();
    caratulas = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    cancelar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

    total.setText("Totales");
    total.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        totalActionPerformed(evt);
      }
    });

    caratulas.setText("Caratulas");
    caratulas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        caratulasActionPerformed(evt);
      }
    });

    jButton4.setText("Idcs");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    cancelar.setText("Atras");
    cancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout ppanelLayout = new javax.swing.GroupLayout(ppanel);
    ppanel.setLayout(ppanelLayout);
    ppanelLayout.setHorizontalGroup(
      ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ppanelLayout.createSequentialGroup()
        .addGroup(ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(ppanelLayout.createSequentialGroup()
            .addGap(49, 49, 49)
            .addGroup(ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(caratulas, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
              .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addGroup(ppanelLayout.createSequentialGroup()
            .addGap(105, 105, 105)
            .addComponent(cancelar)))
        .addContainerGap(48, Short.MAX_VALUE))
      .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    ppanelLayout.setVerticalGroup(
      ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ppanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(caratulas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(16, 16, 16))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(ppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(ppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
    dispose();
  }//GEN-LAST:event_cancelarActionPerformed

  private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
    /*Muestra las estadisticas de papeles, imagenes y campos para el volumen seleccionado*/
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new TotalParaVolumen(volumen).setVisible(true);
      }
    });
  }//GEN-LAST:event_totalActionPerformed

  private void caratulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caratulasActionPerformed

    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new Caratulas(volumen).setVisible(true);
      }
    });
  }//GEN-LAST:event_caratulasActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new IdcTable(volumen).setVisible(true);
      }
    });
  }//GEN-LAST:event_jButton4ActionPerformed
  /**
   * @param args the command line arguments
   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//     */
//    try
//      {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//        {
//        if ("Nimbus".equals(info.getName()))
//          {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//          }
//        }
//      } catch (ClassNotFoundException ex)
//      {
//      java.util.logging.Logger.getLogger(PanelVolumenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (InstantiationException ex)
//      {
//      java.util.logging.Logger.getLogger(PanelVolumenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (IllegalAccessException ex)
//      {
//      java.util.logging.Logger.getLogger(PanelVolumenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (javax.swing.UnsupportedLookAndFeelException ex)
//      {
//      java.util.logging.Logger.getLogger(PanelVolumenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      }
//    //</editor-fold>
//
//    /* Create and display the form */
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        new PanelVolumenes().setVisible(true);
//      }
//    });
//  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelar;
  private javax.swing.JButton caratulas;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel ppanel;
  private javax.swing.JButton total;
  // End of variables declaration//GEN-END:variables

  private void setFrame(Volumen volumen) {
    VersionEImageIcon vi = new VersionEImageIcon(this, "Panel de control");
    ppanel.setBackground(VersionEImageIcon.setcolor());
    jLabel1.setText("Contenido del volumen: " + volumen.getRuta());
  }
}
