/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package volumen;

import help.VersionEImageIcon;
import entidades.Volumen;
import javax.swing.SwingUtilities;
import sedes.DefineTablaContenidosGenerales;
import help.Write;

/**
 *
 * @author aguilangeles@gmail.com
 */
public class TotalParaVolumen extends javax.swing.JFrame {

  private GetPapelesImagenesYCamposVolumen totales;
  private DefineTablaContenidosGenerales generales;
  private Volumen volumen;
  private String datosTotales;

  /**
   * Creates new form TotalParaVolumen
   *
   * @param volumen
   */
  public TotalParaVolumen(Volumen volumen) {
    initComponents();
    VersionEImageIcon vi = new VersionEImageIcon(this, volumen.getRuta());
    ppanel.setBackground(VersionEImageIcon.setcolor());
    setContenidoTabla(volumen);
    this.volumen = volumen;
    setLocationRelativeTo(null);
    Write.createNewSheet(volumen.getRuta(), guardar);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    ppanel = new javax.swing.JPanel();
    Atras = new javax.swing.JButton();
    guardar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaGenerica = new javax.swing.JTable();
    verSubtipos = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    Atras.setText("Atras");
    Atras.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AtrasActionPerformed(evt);
      }
    });

    guardar.setText("Guardar");
    guardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        guardarActionPerformed(evt);
      }
    });

    tablaGenerica.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null}
      },
      new String [] {
        "Nombre", "Valor"
      }
    ));
    jScrollPane1.setViewportView(tablaGenerica);

    verSubtipos.setText("Ver Campos por Subtipo");
    verSubtipos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        verSubtiposActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout ppanelLayout = new javax.swing.GroupLayout(ppanel);
    ppanel.setLayout(ppanelLayout);
    ppanelLayout.setHorizontalGroup(
      ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ppanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
          .addGroup(ppanelLayout.createSequentialGroup()
            .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(verSubtipos)
            .addGap(39, 39, 39)
            .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    ppanelLayout.setVerticalGroup(
      ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ppanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addGroup(ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(Atras)
          .addComponent(guardar)
          .addComponent(verSubtipos))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(ppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(ppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
    dispose();
  }//GEN-LAST:event_AtrasActionPerformed

  private void verSubtiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verSubtiposActionPerformed
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        new TablaDeSubtipo(volumen).setVisible(true);
      }
    });
  }//GEN-LAST:event_verSubtiposActionPerformed

  private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
    Write.writeReport(datosTotales);
  }//GEN-LAST:event_guardarActionPerformed
  /**
   * @param args the command line arguments
   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//     */
//    try
//      {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//        {
//        if ("Nimbus".equals(info.getName()))
//          {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//          }
//        }
//      } catch (ClassNotFoundException ex)
//      {
//      java.util.logging.Logger.getLogger(TotalParaVolumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (InstantiationException ex)
//      {
//      java.util.logging.Logger.getLogger(TotalParaVolumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (IllegalAccessException ex)
//      {
//      java.util.logging.Logger.getLogger(TotalParaVolumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (javax.swing.UnsupportedLookAndFeelException ex)
//      {
//      java.util.logging.Logger.getLogger(TotalParaVolumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      }
//    //</editor-fold>
//
//    /* Create and display the form */
//  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Atras;
  private javax.swing.JButton guardar;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPanel ppanel;
  private javax.swing.JTable tablaGenerica;
  private javax.swing.JButton verSubtipos;
  // End of variables declaration//GEN-END:variables

  private void setContenidoTabla(Volumen volumen) {
    this.totales = new GetPapelesImagenesYCamposVolumen(volumen);
    String campos = new GetCamposSegunSedeParaVolumen(volumen).getCampos();
    this.datosTotales = totales.getString() + ", " + campos;
    this.generales = new DefineTablaContenidosGenerales(tablaGenerica, datosTotales);
  }
}
