package archivos;

import help.Write;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import help.VersionEImageIcon;
import idc.TablaNombreValor;

import volumen.VistaVolumenes;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aguilangeles@gmail.com
 */
public class Inicio extends javax.swing.JFrame {

  private static Write write = new Write();
  private String sigla;

  /**
   * Creates new form Inicio
   */
  public Inicio() {
    initComponents();
    setResizable(false);
    VersionEImageIcon vi = new VersionEImageIcon(this, "Selector de opciones");
    panel.setBackground(VersionEImageIcon.setcolor());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panel = new javax.swing.JPanel();
    volumenes = new javax.swing.JButton();
    totalesSede = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    database = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    volumenes.setText(" Volumenes");
    volumenes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        volumenesActionPerformed(evt);
      }
    });

    totalesSede.setText("Totales por Sede");
    totalesSede.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        totalesSedeActionPerformed(evt);
      }
    });

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Seleccione categoria");

    database.setText("Ver DB");
    database.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        databaseActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
    panel.setLayout(panelLayout);
    panelLayout.setHorizontalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
      .addGroup(panelLayout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addComponent(totalesSede, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
        .addComponent(volumenes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(26, 26, 26))
      .addGroup(panelLayout.createSequentialGroup()
        .addGap(156, 156, 156)
        .addComponent(database)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelLayout.setVerticalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(21, 21, 21)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(volumenes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(totalesSede, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
        .addComponent(database)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void totalesSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalesSedeActionPerformed
    getJOptionPane();
  }//GEN-LAST:event_totalesSedeActionPerformed

  private void volumenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumenesActionPerformed
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new VistaVolumenes(database).setVisible(true);
      }
    });
  }//GEN-LAST:event_volumenesActionPerformed

  private void databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseActionPerformed
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new IngresoBaseDeDatos().setVisible(true);
      }
    });
  }//GEN-LAST:event_databaseActionPerformed
  /**
   * @param args the command line arguments
   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//     */
//    try
//      {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//        {
//        if ("Nimbus".equals(info.getName()))
//          {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//          }
//        }
//      } catch (ClassNotFoundException ex)
//      {
//      java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (InstantiationException ex)
//      {
//      java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (IllegalAccessException ex)
//      {
//      java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (javax.swing.UnsupportedLookAndFeelException ex)
//      {
//      java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      }
//    //</editor-fold>
//
//    /* Create and display the form */
////    java.awt.EventQueue.invokeLater(new Runnable() {
////      public void run() {
////        new Inicio().setVisible(true);
////      }
////    });
//  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton database;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel panel;
  private javax.swing.JButton totalesSede;
  private javax.swing.JButton volumenes;
  // End of variables declaration//GEN-END:variables

  private void getJOptionPane() {
    UIManager uim = new UIManager();
    UIManager.put("OptionPane.background", new ColorUIResource(VersionEImageIcon.setcolor()));
    UIManager.put("Panel.background", new ColorUIResource(VersionEImageIcon.setcolor()));
    int seleccion = JOptionPane.showOptionDialog(
            this,
            "Seleccione opcion",
            "Selector de opciones",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            new ImageIcon("Logos/test_100.png"), // null para icono por defecto.
            new Object[]
      {
      "GNA", "OSN"
      }, // null para YES, NO y CANCEL
            "opcion 1");
    if (seleccion != -1)
      {
      int newSeleccion = seleccion + 1;
      if (newSeleccion == 1)
        {
        sigla = "GNA";
        getTotalesPorSede(newSeleccion, sigla);
        } else if (newSeleccion == 2)
        {
        sigla = "OSN";
        getTotalesPorSede(newSeleccion, sigla);
        }
      }
  }

  private void getTotalesPorSede(final int seleccion, final String sigla) {
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new TablaNombreValor(seleccion, sigla).setVisible(true);
      }
    });
  }
}
