/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package idc;

import help.Write;
import help.VersionEImageIcon;
import sedes.DefineTablaContenidosGenerales;
import sedes.IndicesComunesaAmbasSedes;

/**
 *
 * @author aguilangeles@gmail.com
 */
public class TablaNombreValor extends javax.swing.JFrame {

  private DefineTablaContenidosGenerales tablacontenidos;
  private String sigla;
  private String contenido;
  private String nombreIdc;
  private String valoresIdc;

  /**
   * Creates new form TablaNombreValor
   *
   * @param idSede
   * @param sigla
   */
  public TablaNombreValor(int idSede, String sigla) {
    /*Visualiza la sumatoria de campos segun la sede seleccionada*/
    initComponents();
    guardar.setText("Guardar Totales");
    this.sigla = sigla;
    setFrame("Totales de la sede" + "-" + sigla);
    setLocationRelativeTo(null);
    this.contenido = setContenidoTablaPorSede(idSede);
    this.tablacontenidos = new DefineTablaContenidosGenerales(tablaGeneral, contenido);
    Write.createNewSheet("Total Sede " + sigla, guardar);
  }

  public TablaNombreValor(String contenido, String nombreIdc) {
    /*Visualiza el contenido de un idc seleccionado de la jtable */
    initComponents();
    guardar.setText("Guardar Idc");
    setFrame(nombreIdc);
    DefineTablaContenidosGenerales defineTablaContenidosGenerales = new DefineTablaContenidosGenerales(tablaGeneral, contenido);
    this.valoresIdc = contenido;
    this.nombreIdc =nombreIdc;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    ppanel = new javax.swing.JPanel();
    atras = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaGeneral = new javax.swing.JTable();
    guardar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    atras.setText("Atras");
    atras.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        atrasActionPerformed(evt);
      }
    });

    tablaGeneral.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Detalle", "Valor"
      }
    ));
    jScrollPane1.setViewportView(tablaGeneral);
    tablaGeneral.getColumnModel().getColumn(0).setResizable(false);
    tablaGeneral.getColumnModel().getColumn(1).setResizable(false);

    guardar.setText("Guardar");
    guardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        guardarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout ppanelLayout = new javax.swing.GroupLayout(ppanel);
    ppanel.setLayout(ppanelLayout);
    ppanelLayout.setHorizontalGroup(
      ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppanelLayout.createSequentialGroup()
        .addGap(51, 51, 51)
        .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(31, 31, 31)
        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(52, Short.MAX_VALUE))
      .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
    );
    ppanelLayout.setVerticalGroup(
      ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppanelLayout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(atras, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
          .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(ppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(ppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
    dispose();
  }//GEN-LAST:event_atrasActionPerformed

  private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
    boton(evt);
  }//GEN-LAST:event_guardarActionPerformed

  private void boton(java.awt.event.ActionEvent evt) {
    switch (evt.getActionCommand())
      {
      case "Guardar Totales":

        Write.writeReport(contenido);
        break;
      case "Guardar Idc":
        Write.createNewSheet(nombreIdc, guardar);

        Write.writeReport(valoresIdc);
        break;
      }
  }
  /**
   * @param args the command line arguments
   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//     */
//    try
//      {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//        {
//        if ("Nimbus".equals(info.getName()))
//          {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//          }
//        }
//      } catch (ClassNotFoundException ex)
//      {
//      java.util.logging.Logger.getLogger(TablaNombreValor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (InstantiationException ex)
//      {
//      java.util.logging.Logger.getLogger(TablaNombreValor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (IllegalAccessException ex)
//      {
//      java.util.logging.Logger.getLogger(TablaNombreValor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (javax.swing.UnsupportedLookAndFeelException ex)
//      {
//      java.util.logging.Logger.getLogger(TablaNombreValor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      }
//    //</editor-fold>
//
//    /* Create and display the form */
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        new TablaNombreValor(idSede).setVisible(true);
//      }
//    });
//  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton atras;
  private javax.swing.JButton guardar;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPanel ppanel;
  private javax.swing.JTable tablaGeneral;
  // End of variables declaration//GEN-END:variables

  private void setFrame(String titulo) {
    VersionEImageIcon vi = new VersionEImageIcon(this, titulo + "-");
    ppanel.setBackground(VersionEImageIcon.setcolor());
    setLocationRelativeTo(null);
  }

  private String setContenidoTablaPorSede(int idSede) {
    return new IndicesComunesaAmbasSedes(idSede, sigla).getContenido();
  }
}
